---
format:
  typst:
    citeproc: true
    papersize: a4
    page-numbering: false
    margin:
      x: 0.5cm
      y: 0.5cm
    fig-width: 7.2
    fig-height: 10.5
execute:
  echo: false
---

```{r}
#| label: graph-paper
#| out-width: 100%

library(ggplot2)

expand.grid(x = -10:10, panel = 1:6) |>
  transform(y = x) |>
  ggplot(aes(x = x, y = y)) +
  geom_vline(xintercept = 0, linewidth = 1, color = "black") +
  geom_hline(yintercept = 0, linewidth = 1, color = "black") +
  scale_x_continuous(breaks = -10:10, limits = c(-10, 10)) +
  scale_y_continuous(breaks = -10:10, limits = c(-10, 10)) +
  coord_equal() +
  facet_wrap(vars(panel), ncol = 2) +
  theme_void() +
  theme(
    panel.grid.major = element_line(linewidth = 0.5, color = "grey70"),
    strip.text = element_blank(),
    panel.spacing = unit(0.6, "in")
  )
```

```{=typst}
#set page(flipped: true)
#v(1fr)
```

```{r}
#| label: cookies-graph-paper
#| fig-width: 10.7
#| fig-height: 4.4
#| out-width: 100%

cookies <- data.frame(
  happiness = c(0.5, 2, 1, 2.5, 3, 1.5, 2, 2.5, 2, 3),
  cookies = 1:10
)

ggplot(cookies, aes(x = cookies, y = happiness)) +
  labs(x = "Cookies eaten", y = "Happiness") +
  geom_vline(xintercept = 0, linewidth = 1, color = "black") +
  geom_hline(yintercept = 0, linewidth = 1, color = "black") +
  geom_point(size = 5) +
  scale_x_continuous(breaks = -1:12, limits = c(-0.5, 11)) +
  scale_y_continuous(
    breaks = -1:4,
    limits = c(-0.5, 3.5),
    minor_breaks = seq(-1, 4, 0.25)
  ) +
  coord_equal() +
  theme_void(base_family = "Atkinson Hyperlegible Next") +
  theme(
    panel.grid.major = element_line(linewidth = 0.8, color = "grey70"),
    panel.grid.minor.y = element_line(linewidth = 0.1, color = "grey80"),
    axis.text = element_text(size = 12, color = "grey30"),
    axis.text.x = element_text(margin = margin(t = 4)),
    axis.text.y = element_text(margin = margin(r = 4)),
    axis.title = element_text(size = 14, face = "bold"),
    axis.title.x = element_text(margin = margin(t = 8)),
    axis.title.y = element_text(angle = 90, margin = margin(r = 8))
  )
```


```{r}
#| label: residuals-table

library(tinytable)

residuals_table <- rbind(
  cookies$cookies,
  cookies$happiness,
  "",
  "",
  ""
) |>
  as.data.frame() |>
  setNames(paste("Point", 1:10))

residuals_table$Total <- ""

cbind(
  " " = c(
    "Cookies",
    "Happiness",
    "Predicted happiness",
    "Residual",
    "Residual²"
  ),
  residuals_table
) |>
  tt(theme = "grid", width = 1, height = 3) |>
  style_tt(j = 1, bold = TRUE) |>
  style_tt(i = 0, bold = TRUE, align = "c") |>
  style_tt(alignv = "m") |>
  style_tt(j = 2:12, align = "c") |>
  style_tt(i = 1:3, j = 12, background = "grey50")
```

```{=typst}
#v(1fr)
```
